module.exports = Object.freeze({
    WORKER_ERROR: 'WORKER_ERROR',
    WORKER_SUCCESS: 'WORKER_SUCCESS',
    WORKER_LAUNCH: 'WORKER_LAUNCH',
    WORKER_EXIT: 'WORKER_EXIT',
    WORKER_CONSOLE_LOG: 'WORKER_CONSOLE_LOG',
    WORKER_CONSOLE_ERROR: 'WORKER_CONSOLE_ERROR'
});